apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: environment-build
spec:
  timeout: 60m
  steps:
  - env:
    - name: CHART_REPOSITORY
      value: http://jenkins-x-chartmuseum:8080
    image: jenkinsxio/builder-base:{{ .Values.builderTag }}
    name: build
    args:
    - jx
    - step
    - helm
    - build
    resources:
      limits:
        cpu: "0.4"
        memory: 256Mi
      requests:
        cpu: "0.2"
        memory: 128Mi
    workingDir: /workspace/env